language: node_js
node_js:
  - "12.16"
addons:
  ssh_known_hosts: 165.22.215.143
before_install:
  - openssl aes-256-cbc -K $encrypted_82a198b60ea6_key -iv $encrypted_82a198b60ea6_iv
    -in corona_rsa.enc -out corona_rsa -d
  - chmod 600 corona_rsa
  - mv corona_rsa ~/.ssh/id_rsa
  - cd client
install:
  - npm install
script:
  - "true"
after_success:
  - npm run build
  - cd ..
  - bash ./deploy.sh
notifications:
  slack:
    rooms:
      secure: O0Chnn5uD2KhkMnnfrH/EWkFjZBbgPgSpy2QlcNfl2rHrphQLSb2v/Nt2dEA4Qu6u/XSAFnaCWpTgSXqsY1diEYE64HaRA2uc0pXlS8n3PK06i8vImgI5FdbiVaUdYQ88FpynCE0+ob2i4IwpWiQtIBtLkBxJ5YUip1cxCN9p7bKxPFn9LHFXNnJHW62KoU6UIC04IaBg6OlqLjk3WbQ4l/oxjdy9P6MLJs+/xQZRyicvTIQs2rSVvf7d2XSv9GOQqYX87s1Cy7/CbuDvR7yPyEe7tx2xlZImwAKz38D/t+HFle0jRL8PMZsE1vchr2NqxGK5Z2oFJwAWUSk9yvl55zDLUXAAWFsaV21+rbndY4yDAx3Q/3CZjxkMippqqJSYRQooJVDXXlqR4x1sZA1ZOpRnO89mBBM1G679lBX9563U/vK6rxNR8JmB9MTpv53ANBMl3rROXDT8z0ggGDodqiMYl4f9f9KhppkNXMtpjWgUkv/1Ghl+qw7YEahmDMUcdcrD48ju058vSl5HJvO/xcp2pZ90LdZI+zu3OBj+Y0SJoalTqfwEvZI6Bdse/ZMbQsh+AfMTLWBdXbWDn7iEwA71mWS/2IebWcDHde5DHHqxWD9ThyLLv3pyDMqkmBe/jx3zZ7GpzZpN1BfmbTioZEH7W8BQ6GXyM0UUOAatl0=
